version: '2'
services:
  web:
    build:
      context: ./
      args:
        DOMAIN_NAME: 'your domain name'
        USER_MAIL: 'your mail address'
    volumes:
      - ../app:/app/
      - ./cert:/cert/
    ports:
      - 443:443
      - 80:80
    environment:
      CHANNEL_ACCESS_TOKEN: 'your line CHANNEL_ACCESS_TOKEN'
      CHANNEL_SECRET: 'your line CHANNEL_SECRET'
